import { Agent } from "kaibanjs";
import { searchTool } from "./tools.js";

export const researchAgent = new Agent({
    name: 'Jack',
    role: 'News Researcher',
    goal: 'Find and summarize the latest news on a given topic',
    background: 'Experienced in data analysis and information gathering',
    tools: [searchTool],
    llmConfig: {
        provider: 'google',
        model: 'gemini-2.0-flash',
        maxRetries: 3,
        temperature: 0.7,
    }
});

export const writerAgent = new Agent({
    name: 'Kai',
    role: 'Content Creator',
    goal: 'Create engaging blog posts with unique titles and engaging content based on the gathered latest news.',
    background: 'Skilled in writing and content creation',
    llmConfig: {
        provider: 'google',
        model: 'gemini-2.0-flash',
        maxRetries: 3,
        temperature: 0.7,
    }
});

export const validatorAgent = new Agent({
    name: 'Ava',
    role: 'Content Validator',
    goal: 'Validate engaging blog posts generated by the content creator',
    background: 'Skilled in validating and analysing engagment of content',
    llmConfig: {
        provider: 'google',
        model: 'gemini-2.0-flash',
        maxRetries: 3,
        temperature: 0.7,
    }
});